name: primjer
on:
  label:
    types: [created]
  issues:
    types: [opened]
jobs:
  posao:
    runs-on: ubuntu-latest
    steps:
      - name: prvi_korak
        run: echo "Trigger - ${{ github.event_name }}, user - ${{ github.actor }}, date - ${{ date }}"
